core/apps/almon/urls.py
from django.urls import path
from core.apps.almon import views

app_name = 'almon'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),

    #  user passwords
    path('add-password/', views.AddNewPasswordView.as_view(), name="add-password"),
    path('manage-passwords/', views.ManagePasswordsView.as_view(), name="manage-passwords"),
    path('update-password/<int:pk>', views.UpdatePasswordView.as_view(), name='update-password'),
    path('delete-password/<int:pk>', views.DeletePasswordView.as_view(), name="delete-password"),
    path('search/', views.SearchPasswordView.as_view(), name='search'),

    # path for generating random password
    path('generate-password/', views.generate_password, name='generate-password'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.apps.almon.urls', namespace='almon')),
    path('users/', include('core.apps.users.urls', namespace='users')),
]

core/apps/almon/models.py
from django.db import models
from django.conf import settings
from .cryptor import Cryptor
from django.utils.text import slugify


class Category(models.Model):
    name = models.CharField(max_length=30)
    slug = models.SlugField(unique=True, max_length=30)

    class Meta:
        verbose_name_plural = "Categories"

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        super(Category, self).save(*args, **kwargs)

    def __str__(self):
        return self.name


class Almon(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT, null=False, blank=False)
    category = models.ForeignKey(Category, on_delete=models.CASCADE, default=1)

    email = models.EmailField(max_length=255)
    username = models.CharField(max_length=100, null=True, blank=True)
    password = models.CharField(max_length=100)

    application_type = models.CharField(max_length=30)
    application_name = models.CharField(max_length=30, blank=True)

    date_created = models.DateTimeField(auto_now_add=True)
    date_last_updated = models.DateTimeField(auto_now=True)

    @property
    def decrypted_email(self):
        return Cryptor.decrypt(self.email)

    @property
    def decrypted_password(self):
        return Cryptor.decrypt(self.password)

    def __str__(self):
        return f'{self.user}'

core/apps/almon/forms.py
from django import forms
from .models import Almon


class AlmonForm(forms.ModelForm):
    class Meta:
        model = Almon
        # fields = '__all__'
        exclude = ['user']

    def __init__(self, *args, **kwargs):
        super(AlmonForm, self).__init__(*args, **kwargs)

        self.fields['email'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Email'}
        )
        self.fields['category'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Category'}
        )
        self.fields['username'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Username'}
        )
        self.fields['password'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Password'}
        )
        self.fields['application_type'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'e.g., Website, Mobile App, Desktop Application'}
        )
        self.fields['application_name'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'e.g., Google, WhatsApp, PyCharm'}
        )

core/apps/almon/views.py
from django.contrib import messages
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.messages.views import SuccessMessageMixin
from django.db.models import Q
from django.http import JsonResponse
from django.shortcuts import get_object_or_404
from django.urls import reverse, reverse_lazy
from django.views.generic import CreateView, DeleteView, UpdateView, TemplateView, ListView

from .models import Almon, Category
from .forms import AlmonForm
from .cryptor import Cryptor
from .utils import generate_random_password

from django.utils.decorators import method_decorator
from django.views.decorators.cache import cache_control

from core.apps.users.forms import UpdatePasswordForm  # user app


@method_decorator(cache_control(no_cache=True, must_revalidate=True, no_store=True), name='dispatch')
class HomePageView(LoginRequiredMixin, TemplateView):
    template_name = 'almon/home.html'


@method_decorator(cache_control(no_cache=True, must_revalidate=True, no_store=True), name='dispatch')
class AddNewPasswordView(LoginRequiredMixin, CreateView):
    model = Almon
    form_class = AlmonForm
    template_name = 'almon/add-new-password.html'
    success_url = reverse_lazy('almon:add-password')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['categories'] = Category.objects.all()  # Pass all categories to the template
        return context

    def form_valid(self, form):
        form.instance.user = self.request.user
        print(form)
        messages.success(self.request, f"New password added for {form.cleaned_data['application_name']}")
        return super().form_valid(form)


@method_decorator(cache_control(no_cache=True, must_revalidate=True, no_store=True), name='dispatch')
class UpdatePasswordView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    model = Almon
    form_class = UpdatePasswordForm
    template_name = 'almon/update-password.html'
    success_message = 'Password updated successfully.!'

    def get_object(self, queryset=None):
        return get_object_or_404(Almon, id=self.kwargs.get('pk'))

    def get_success_url(self):
        return reverse('almon:update-password', kwargs={'pk': self.object.id})

    def form_valid(self, form):
        instance = self.get_object()

        if form.cleaned_data['email'] != instance.decrypted_email:
            form.instance.email = Cryptor.encrypt(form.cleaned_data['email'])

        if form.cleaned_data['password'] != instance.decrypted_password:
            form.instance.password = Cryptor.encrypt(form.cleaned_data['password'])

        return super().form_valid(form)


@method_decorator(cache_control(no_cache=True, must_revalidate=True, no_store=True), name='dispatch')
class DeletePasswordView(LoginRequiredMixin, DeleteView):
    model = Almon
    template_name = 'almon/manage-passwords.html'
    success_url = reverse_lazy('almon:manage-passwords')
    context_object_name = 'password'

    def delete(self, request, *args, **kwargs):
        messages.success(self.request, 'Password Deleted.!')
        return super().delete(request, *args, **kwargs)


@method_decorator(cache_control(no_cache=True, must_revalidate=True, no_store=True), name='dispatch')
class SearchPasswordView(LoginRequiredMixin, ListView):
    queryset = Almon
    template_name = 'almon/search.html'
    context_object_name = 'passwords'

    def get_queryset(self):
        queryset = Almon.objects.filter(user=self.request.user)
        return queryset

    def post(self, request, *args, **kwargs):
        queryset = self.get_queryset()
        searched = self.request.POST.get("password_search", "")
        self.object_list = queryset
        if searched:
            queryset = queryset.filter(Q(username__icontains=searched) | Q(email__icontains=searched))
        return self.render_to_response(self.get_context_data(object_list=queryset))


class ManagePasswordsView(LoginRequiredMixin, ListView):
    model = Almon
    context_object_name = 'all_passwords'
    template_name = 'almon/manage-passwords.html'

    def get_queryset(self, queryset=None):
        return Almon.objects.filter(user=self.request.user)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        # Get all categories
        categories = Category.objects.all()
        context['categories'] = categories

        # Filter passwords based on selected category
        selected_category_id = self.request.GET.get('category')
        user_passwords = self.get_queryset()

        if selected_category_id:
            user_passwords = user_passwords.filter(category_id=selected_category_id)

        # Sorting logic remains the same
        sort_order = self.request.GET.get('sort_order', 'desc')
        if sort_order == 'asc':
            user_passwords = user_passwords.order_by('date_created')
        else:
            user_passwords = user_passwords.order_by('-date_created')

        context['all_passwords'] = user_passwords
        context['sort_order'] = sort_order
        context['selected_category_id'] = selected_category_id

        if not user_passwords:
            context['no_password'] = "No password available. Please add a password."

        return context


# generate random password
def generate_password(request):
    password = generate_random_password()
    return JsonResponse(
        {'password': password}
    )

templates/almon/add-new-password.html
{% extends 'base.html' %}
{% load static %}
{#{% load utility_tags %}#}

{% block content %}
    <section class="h-100 h-custom">
        <div class="container py-2 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
{#                        <img class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"#}
{#                             alt="Sample photo" src={% static '/assets/img/add-password.png' %}>#}
                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Add new password</h3>
                            {% if messages %}
                                <div class="alert alert-primary" role="alert">
                                    {% for message in messages %}
                                        {{ message }}
                                    {% endfor %}
                                </div>
                            {% endif %}
                            
                        {% if user.is_authenticated %}
                            <form method="POST" action="/add-password/" class="px-md-2">
                                {% csrf_token %}
                                
                                <div class="form-floating mb-4">
                                    <select name="{{ form.category.name }}" class="form-select" id="{{ form.category.id_for_label }}">
                                        {% for category in categories %}
                                            <option value="{{ category.id }}">{{ category.name }}</option>
                                        {% endfor %}
                                    </select>
                                    <label for="{{ form.category.id_for_label }}">
                                        {{ form.category.label }}
                                        <span class="text-muted small">(Required)</span>
                                    </label>
                                </div>
                                
                                <!-- email -->
                                
                                <div class="form-floating mb-4">
                                    {{ form.email }}
                                    <label for="{{ form.email.id_for_label }}">
                                        {{ form.email.label }}
                                        <span class="text-muted small">(Required)</span>
                                    </label>
                                </div>
                                
                                <!-- username -->
                               <div class="form-floating mb-4">
                                    {{ form.username }}
                                    <label for="{{ form.username.id_for_label }}">
                                        {{ form.username.label }}
                                    </label>
                                </div>
                                
                                <!-- password -->
                                <div class="input-group mb-4">
                                    <div class="form-floating">
                                        {{ form.password }}
                                        <label for="{{ form.password.id_for_label }}">Password</label>
                                    </div>
                                    <button type="button" id="generate-password-button" class="btn btn-primary" onclick="generatePasswordHandler()">
                                        Generate
                                    </button>
                                </div>
                                <div class="form-floating mb-4">
                                    {{ form.application_type }}
                                    <label for="{{ form.application_type.id_for_label }}">
                                        {{ form.application_type.label }}
                                        <span class="text-muted small">(Required)</span>
                                    </label>
                                </div>
                                
                                <div class="form-floating mb-4">
                                    {{ form.application_name }}
                                    <label for="{{ form.application_name.id_for_label }}">
                                        {{ form.application_name.label }}
                                    </label>
                                </div>

                                <button type="submit" class="btn btn-success btn-md mb-1">Submit</button>
                            </form>
                        {% else %}
                            <h1> Please Login/Register</h1>
                        {% endif %}
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>    
{% endblock %}

templates/almon/home.html
{% extends 'base.html' %}
{% load static %}


{% block content %}
    <section id="hero" class="hero d-flex align-items-center">
        <div class="container">
            <div class="row">
                <div class="col-lg-6 d-flex flex-column justify-content-center">
                    <h1>Welcome to your password manager app</h1>
                    <h2>Manage your all passwords from one place. Secure, fast and useful.</h2>
                    <div class="d-md-flex gap-2">
                        <div class="text-center text-lg-start">
                            <a href="{% url 'almon:add-password' %}"
                               class="btn-get-started d-inline-flex align-items-center justify-content-center align-self-center">
                                <span>Add</span>
                                <i class="fa fa-plus"></i>
                            </a>
                        </div>
                        <div class="text-center text-lg-start">
                            <a href="{% url 'almon:manage-passwords' %}"
                               class="btn-get-started d-inline-flex align-items-center justify-content-center align-self-center">
                                <span>View all</span>
                                <i class="fas fa-eye"></i>
                            </a>
                        </div>
                    </div>
                </div>
                <div class="col-lg-6 hero-img">
                    <img class="img-fluid" alt="home-img" src={% static '/assets/img/Vault-rafiki.svg' %}>
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/almon/manage-passwords.html
{% extends 'base.html' %}
{% load decrypt_tags %}
{% load static %}

{% block content %}

    <section class="container">
    
        <div class="mt-2 mb-4">
            <h3>Manage passwords</h3>
        
                <form id="filterForm" method="get">
                    <label for="category">Filter by Category:</label>
                    <select name="category" id="category" onchange="submitFilterForm()">
                    <option value="" {% if not selected_category_id %}selected{% endif %}>
                        All Categories
                    </option>
                        {% for category in categories %}
                            <option value="{{ category.id }}" {% if category.id == selected_category_id %}selected{% endif %}>
                                {{ category.name }}
                            </option>
                        {% endfor %}
                    </select>
                </form>
        
            <hr/>
        </div>

        <!-- -->
        {% if all_passwords %}
            <div class="table-responsive">
                <table class="table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Email</th>
                        <th scope="col">Username</th>
                        <th scope="col">Password</th>
                        <th scope="col" class="text-nowrap">Type</th>
                        <th scope="col" class="text-nowrap">Name</th>
                        <th scope="col">
                            <a style="text-decoration: none;"
                                           href="{% url 'almon:manage-passwords' %}?sort_order={% if sort_order|default:"desc" == "desc" %}asc{% else %}desc{% endif %}">
                            Last updated
                            </a>
                        </th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    {% for password in all_passwords %}
                        <tbody>
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ password.email| decrypt_password }}</td>
                            <td>{{ password.username }}</td>
                            <td>
                                <div class="input-group input-group-sm">
                                    <label for=value="{{ password.password }}"></label>
                                    <input class="form-control" type="password" id={{ forloop.counter }}
                                           value="{{ password.password|decrypt_password }}" readonly>
                                    <div class="input-group-append">
                                        <button onclick="toggleView({{ forloop.counter }})" class="btn btn-sm btn-outline-secondary" type="button" id="view-password">
                                            <i id="icon-{{ forloop.counter }}" class="fas fa-eye"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td>{{ password.application_type }}</td>
                            <td>
                                {{ password.application_name }}
                            </td>
                            <td class="text-nowrap">{{ password.date_last_updated }}</td>
                            <td>
                              
                                <a class="btn btn-warning btn-sm" href="{% url 'almon:update-password' password.id %}">
                                    Edit
                                </a>
                                <td>
                                    <form method="post" action="{% url 'almon:delete-password' password.id %}" class='d-inline'>
                                        {% csrf_token %}
                                        <button type="submit" class="btn btn-danger btn-sm">
                                            Delete
                                        </button>
                                    </form>
                                </td>
                        </tr>
                        </tbody>
                    {% endfor %}

                </table>
            </div>
        {% else %}
            <div class="w-50 mx-auto">
                <img src={% static '/assets/img/no-data.svg' %} alt="no-data">
            </div>
        {% endif %}
    </section>
    
    <script>
    document.addEventListener("DOMContentLoaded", function () {
        document.getElementById("category").value = "{{ selected_category_id }}";
    });
    function submitFilterForm() {
        document.getElementById('filterForm').submit();
    }
    </script>

{% endblock %}

templates/almon/search.html
{% extends 'base.html' %}
{% load static %}
{% load decrypt_tags %}

{% block content %}
    <section class="container">
        <div class="d-flex h-100 w-100 mt-2 mb-5">
            <div class="align-self-center mx-auto">
                <form method="POST" action="{% url "almon:search" %}">
                    {% csrf_token %}
                    <div class="input-group">
                        <input type="search" class="form-control rounded" name="password_search" placeholder="Search by username or email"
                               aria-label="Search"
                               aria-describedby="search-addon"/>
                        <button type="submit" class="btn btn-outline-primary">Search</button>
                    </div>
                </form>
            </div>
        </div>

        {% if messages %}
            <div class="w-50 mx-auto">
                <div class="alert alert-primary text-center" role="alert">
                    {% for message in messages %}
                        {{ message }}
                    {% endfor %}
                </div>
            </div>
        {% endif %}

        {% if  passwords %}
            <div class="table-responsive">
                <table class="table table table-hover">
                    <thead>
                    <tr>
                        <th scope="col">#</th>
                        <th scope="col">Email</th>
                        <th scope="col">Username</th>
                        <th scope="col">Password</th>
                        <th scope="col" class="text-nowrap">Type</th>
                        <th scope="col">Name</th>
                        <th scope="col">Action</th>
                    </tr>
                    </thead>
                    {% for password in passwords %}
                        <tbody>
                        <tr>
                            <td>{{ forloop.counter }}</td>
                            <td>{{ password.email|decrypt_password }}</td>
                            <td>{{ password.username }}</td>
                            <td>
                                <div class="input-group input-group-sm">
                                    <input class="form-control" type="password" id={{ forloop.counter }}
                                            value="{{ password.password|decrypt_password }}" disabled readonly>
                                    <div class="input-group-append">
                                        <button onclick="toggleView({{ forloop.counter }})"
                                                class="btn btn-sm btn-outline-secondary" type="button"
                                                id="view-password">
                                            <i id="icon-{{ forloop.counter }}" class="fas fa-eye"></i>
                                        </button>
                                    </div>
                                </div>
                            </td>
                            <td>{{ password.application_type }}</td>
                            <td>
                                {{ password.application_name }}
                            </td>
                            <td>
                                <a class="btn btn-warning btn-sm" href="{% url 'almon:update-password' password.id %}">
                                    Edit
                                </a>
                            </td>
                        </tr>
                        </tbody>
                    {% endfor %}
                </table>
            </div>
        {% else %}
            <div class="w-50 mx-auto">
                <img src={% static '/assets/img/search.svg' %} alt="no-data">
            </div>
        {% endif %}
    </section>
{% endblock %}

templates/almon/update-password.html
{% extends 'base.html' %}
{% load static %}
{#{% load decrypt_tags %}#}


{% block content %}
    <section class="h-100 h-custom">
        <div class="container py-2 h-100">
            <div class="row d-flex justify-content-center align-items-center h-100">
                <div class="col-lg-8 col-xl-6">
                    <div class="card rounded-3">
                        <img class="w-100" style="border-top-left-radius: .3rem; border-top-right-radius: .3rem;"
                             alt="Sample photo" src={% static '/assets/img/add-password.png' %}>
                        <div class="card-body p-4 p-md-5">
                            <h3 class="mb-4 pb-2 pb-md-0 mb-md-5 px-md-2">Edit password</h3>

                            <form method="POST" class="px-md-2">
                                {% csrf_token %}

                                {% if messages %}
                                    <div class="alert alert-primary" role="alert">
                                        {% for message in messages %}
                                            {{ message }}
                                        {% endfor %}
                                    </div>
                                {% endif %}
                            
                                <!-- email -->
                                <div class="form-floating mb-4">
                                    <input type="text" class="form-control" id="email" name="email"
                                        value="{{ almon.decrypted_email }}">
                                    <label for="email">Email</label>
                                </div>
                            
                                <!-- username -->
                                <div class="form-floating mb-4">
                                    {{ form.username }}
                                    <label for="username">Username</label>
                                </div>

                                <!-- password -->
                                <div class="form-floating mb-4">
                                    <input type="text" class="form-control" id="password" name="password"
                                        value="{{ almon.decrypted_password }}">
                                    <label for="password">Password</label>
                                </div>
                            
                                <!-- application type -->
                                <div class="form-floating mb-4">
                                    {{ form.application_type }}
                                    <label for="password">Application type</label>
                                </div>

                                
                                <div class="form-floating mb-4">
                                    {{ form.application_name }}
                                    <label for="website_name">Application name</label>
                                </div>

                                {% if form.errors %}
                                    <div class="text-danger">
                                        {% for field in form %}
                                            {% for error in field.errors %}
                                                <p>{{ field.label }}: {{ error }}</p>
                                            {% endfor %}
                                        {% endfor %}
                                    </div>
                                {% endif %}

                                <div class="d-flex justify-content-between">
                                    <button type="submit" class="btn btn-success btn-md mb-1 mr-1">Update</button>
                                    <a class="btn btn-primary btn-md mb-1" href="{% url "almon:manage-passwords" %}">Back to Home</a>
                                </div>

                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}