core/apps/almon/urls.py
from django.urls import path
from core.apps.almon import views

app_name = 'almon'

urlpatterns = [
    path('', views.HomePageView.as_view(), name='home'),

    #  user passwords
    path('add-password/', views.AddNewPasswordView.as_view(), name="add-password"),
    path('manage-passwords/', views.ManagePasswordsView.as_view(), name="manage-passwords"),
    path('update-password/<int:pk>', views.UpdatePasswordView.as_view(), name='update-password'),
    path('delete-password/<int:pk>', views.DeletePasswordView.as_view(), name="delete-password"),
    path('search/', views.SearchPasswordView.as_view(), name='search'),

    # path for generating random password
    path('generate-password/', views.generate_password, name='generate-password'),
]

core/apps/users/urls.py
from django.urls import path
from core.apps.users import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .forms import PasswdResetConfirmForm, PasswdResetForm

app_name = 'users'

urlpatterns = [
    # users account
    # path('', views.UserLoginView.as_view(), name='index'),
    path('login/', views.user_login_view, name='login'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('logout/', views.logout_view, name="logout"),

    # account activation urls
    path('confirm-email/', views.UserAccountEmailConfirmView.as_view(), name='confirm-email'),
    path('activate/<uid>/<token>/', views.UserAccountActivationView.as_view(), name='activate'),

    # Password reset URLs
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password-reset/password_reset_form.html',
        email_template_name='users/password-reset/password_reset_email.html',
        success_url='password-reset-email-confirm/',
        form_class=PasswdResetForm
    ), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password-reset/password_reset_confirm.html',
        success_url='/password-reset-complete/',
        form_class=PasswdResetConfirmForm
    ), name='password_reset_confirm'),
    path('password-reset/password-reset-email-confirm/',
         TemplateView.as_view(template_name="users/password-reset/reset_status.html"),
         name='password_reset_done'),
    path('password-reset/password-reset-complete/',
         TemplateView.as_view(template_name="users/password-reset/reset_status.html"),
         name='password_reset_complete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.apps.almon.urls', namespace='almon')),
    path('users/', include('core.apps.users.urls', namespace='users')),
]

templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- Fontawesome -->
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css"
          integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">

    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    
    <title>Password Manager</title>
</head>
<body>
<header>
    <nav class="navbar navbar-expand-lg bg-light">
        <div class="container">
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarTogglerDemo01"
                    aria-controls="navbarTogglerDemo01" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarTogglerDemo01">
                <a class="navbar-brand" href="{% url 'almon:home' %}">
                    <img src={% static '/assets/img/icon/logo.png' %} alt="vault" width="60" height="60"/>
                </a>
                <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
                    {% if user.is_authenticated %}
                        
                        <li class="nav-item">
                                <a class="nav-link {% if request.path == '/add-password/' %}active{% endif %}"
                                   aria-current="page" href="{% url 'almon:add-password' %}">Add password</a>
                        </li>
                
                        
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/manage-passwords/' %}active{% endif %}"
                               aria-current="page" href="{% url 'almon:manage-passwords' %}">Manage passwords</a>
                        </li>
                
                        
                        <li class="nav-item">
                            <a class="nav-link {% if request.path == '/search/' %}active{% endif %}"
                               href="{% url 'almon:search' %}">Search</a>
                        </li>
                
                
                        <li class="nav-item">
                            <a class="nav-link" href="{% url 'users:logout' %}">Logout</a>
                        </li>
                    {% else %}
                
                         <li class="nav-item">
                            <a class="nav-link {% if request.path == '/register/' %}active{% endif %}"
                               href="{% url 'users:register' %}">Register</a>
                        </li>
                    {% endif %}
                </ul>
            </div>
        </div>
    </nav>
</header>

<main class="mt-3">
    {% block content %}

    {% endblock %}
</main>

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
<script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
<script src="{% static 'assets/js/script.js' %}"></script>
</body>
</html>