core/apps/users/urls.py
from django.urls import path
from core.apps.users import views
from django.views.generic import TemplateView
from django.contrib.auth import views as auth_views
from .forms import PasswdResetConfirmForm, PasswdResetForm

app_name = 'users'

urlpatterns = [
    # users account
    # path('', views.UserLoginView.as_view(), name='index'),
    path('login/', views.user_login_view, name='login'),
    path('register/', views.UserRegistrationView.as_view(), name='register'),
    path('logout/', views.logout_view, name="logout"),

    # account activation urls
    path('confirm-email/', views.UserAccountEmailConfirmView.as_view(), name='confirm-email'),
    path('activate/<uid>/<token>/', views.UserAccountActivationView.as_view(), name='activate'),

    # Password reset URLs
    path('password-reset/', auth_views.PasswordResetView.as_view(
        template_name='users/password-reset/password_reset_form.html',
        email_template_name='users/password-reset/password_reset_email.html',
        success_url='password-reset-email-confirm/',
        form_class=PasswdResetForm
    ), name='password_reset'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(
        template_name='users/password-reset/password_reset_confirm.html',
        success_url='/password-reset-complete/',
        form_class=PasswdResetConfirmForm
    ), name='password_reset_confirm'),
    path('password-reset/password-reset-email-confirm/',
         TemplateView.as_view(template_name="users/password-reset/reset_status.html"),
         name='password_reset_done'),
    path('password-reset/password-reset-complete/',
         TemplateView.as_view(template_name="users/password-reset/reset_status.html"),
         name='password_reset_complete'),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('core.apps.almon.urls', namespace='almon')),
    path('users/', include('core.apps.users.urls', namespace='users')),
]

core/apps/users/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser, BaseUserManager, PermissionsMixin


class CustomUserManager(BaseUserManager):
    def create_user(self, email, password=None, **extra_fields):
        if not email:
            raise ValueError("The email field must be set")
        email = self.normalize_email(email)
        user = self.model(email=email, **extra_fields)
        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_staff(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", False)

        return self.create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        extra_fields.setdefault("is_staff", True)
        extra_fields.setdefault("is_superuser", True)

        return self.create_user(email, password, **extra_fields)


class CustomUserModel(AbstractUser, PermissionsMixin):
    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    email = models.EmailField(unique=True)
    objects = CustomUserManager()

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = ['username']

    class Meta:
        verbose_name = 'User Account'
        verbose_name_plural = 'User Accounts'

    def __str__(self):
        return self.username

core/apps/users/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import (
    UserCreationForm,
    AuthenticationForm,
    PasswordResetForm,
    SetPasswordForm
)
from django.utils.translation import gettext_lazy as _
from core.apps.users.mixins import EmailMixin
from core.apps.almon.models import Almon

User = get_user_model()


class RegistrationForm(UserCreationForm, EmailMixin):
    class Meta:
        model = User
        fields = ('username', 'email',)

        widgets = {
            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Username'
            }),
            'email': forms.EmailInput(attrs={
                'class': 'form-control',
                'placeholder': 'example@company.com'
            })
        }

    def __init__(self, *args, **kwargs):
        self.request = kwargs.pop('request')
        super(RegistrationForm, self).__init__(*args, **kwargs)

        self.fields['password1'].widget.attrs.update(
            {'class': 'form-control mb-3', 'placeholder': 'Password'}
        )
        self.fields['password2'].widget.attrs.update(
            {'class': 'form-control', 'placeholder': 'Repeat Password'}
        )

    def save(self, commit=True):
        """Send activation email after creating the user."""
        user = super().save(commit=False)
        user.is_active = False
        if commit:
            user.save()
            self.send_activation_email(self.request, user)
        return user


class LoginForm(AuthenticationForm):
    username = forms.EmailField(label=_("Your Email"),
                                widget=forms.TextInput(attrs={"class": "form-control", "placeholder": "Email"}))
    password = forms.CharField(
        label=_("Your Password"),
        strip=False,
        widget=forms.PasswordInput(attrs={"class": "form-control", "placeholder": "Password"}),
    )


class UpdatePasswordForm(forms.ModelForm):
    class Meta:
        model = Almon
        fields = ['id', 'email', 'username', 'password', 'application_type', 'application_name']

        widgets = {
            'email': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Email'
            }),

            'username': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'Username'
            }),
            'password': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'password'
            }),
            'application_type': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'application type',
            }),
            'application_name': forms.TextInput(attrs={
                'class': 'form-control',
                'placeholder': 'application name',
            }),
        }


class PasswdResetForm(PasswordResetForm):
    email = forms.EmailField(max_length=254, widget=forms.TextInput(
        attrs={'class': 'form-control mb-3', 'placeholder': 'Email', 'id': 'form-email'}))

    def clean_email(self):
        email = self.cleaned_data['email']
        u = User.objects.filter(email=email)
        if not u:
            raise forms.ValidationError(
                'Unfortunately we can not find that email address')
        return email


class PasswdResetConfirmForm(SetPasswordForm):
    new_password1 = forms.CharField(
        label='New password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-newpass'}))
    new_password2 = forms.CharField(
        label='Repeat password', widget=forms.PasswordInput(
            attrs={'class': 'form-control mb-3', 'placeholder': 'New Password', 'id': 'form-new-pass2'}))

core/apps/users/views.py
from django.contrib.auth.views import LoginView
from django.shortcuts import redirect, render
from django.contrib.auth import logout, login, get_user_model
from .forms import RegistrationForm, LoginForm, UpdatePasswordForm
from django.views.decorators.cache import cache_control
from django.contrib import messages

from .tokens import Token_Generator
from .mixins import OnlyUnauthenticatedMixin
from django.utils.http import urlsafe_base64_decode
from django.views.generic import CreateView, TemplateView
from django.http import HttpResponseRedirect, HttpResponse

User = get_user_model()


class UserAccountEmailConfirmView(TemplateView):
    template_name = 'users/registration/register_email_confirm.html'


class UserAccountActivationView(TemplateView):
    def get(self, request, *args, **kwargs):
        try:
            user_id = urlsafe_base64_decode(kwargs['uid']).decode()
            user = User.objects.get(pk=user_id)

            if Token_Generator.check_token(user, kwargs['token']):
                if not user.is_active:
                    user.is_active = True
                    user.save()
                    login(request, user)
                    return HttpResponseRedirect('/')
                else:
                    return HttpResponse('User is already active!')

            else:
                return HttpResponse('Activation link is invalid!')

        except User.DoesNotExist:
            return HttpResponse('User not found!')

        except (KeyError, TypeError, ValueError):
            return HttpResponse('Error in activation!')


class UserLoginView(LoginView):
    form_class = LoginForm
    template_name = 'users/login.html'

    def form_valid(self, form):
        print(form.cleaned_data['username'])
        return super(UserLoginView, self).form_valid(form)


def user_login_view(request):
    if request.user.is_authenticated:
        return redirect('/')
    return UserLoginView.as_view()(request)


def reverse_lazy(param):
    pass


class UserRegistrationView(CreateView, OnlyUnauthenticatedMixin):
    form_class = RegistrationForm
    template_name = 'users/register.html'
    success_url = '/users/confirm-email/'

    def get_form_kwargs(self):
        """Send request to the form."""
        kwargs = super().get_form_kwargs()
        kwargs['request'] = self.request
        return kwargs


# logout
@cache_control(no_cache=True, must_revalidate=True, no_store=True)
def logout_view(request):
    if not request.user.is_authenticated:
        return redirect('/')
    logout(request)
    return redirect('/')

templates/users/login.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="vh-100">
        <div class="container py-5 h-100">
            <div class="row d-flex align-items-center justify-content-center h-100">
                <div class="col-md-8 col-lg-7 col-xl-6 mb-3">
                    <img src={% static '/assets/img/login.svg' %} class="img-fluid" alt="Phone image">
                </div>
                <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                    <div class="d-flex flex-column justify-content-center mb-4 login-header">
                        <h2>Welcome to password manager app. To use this app please log in or signup.</h2>
                    </div>
                    <form method="POST">
                        {% csrf_token %}
                    
                            {% if form.errors %}
                              <div class="alert alert-primary" role="alert">
                                Error: Email or Password not correct!
                              </div>
                            {% endif %}
                    
                        <!-- Email input -->
                        <div class="form-floating mb-4">
                            {{ form.username }}
                            <label for="floatingInput">Email</label>
                        </div>

                        <!-- Password input -->
                        <div class="form-floating mb-4">
                            {{ form.password }}
                            <label for="floatingPassword">Password</label>
                        </div>

                        <!-- Submit button -->
                        <button type="submit" class="btn btn-primary btn-lg w-100">Sign In</button>

                        <div class="divider d-flex align-items-center my-3">
                            <p class="text-center fw-bold mx-3 mb-0 text-muted">OR</p>
                        </div>
                    
                        <div class="flex-column justify-content-center mx-auto pb-3">
                            <div class="text-center">
                                <a href="{% url "users:register" %}">Create an account</a>
                            </div>
                            <div class="text-center">
                                <a href="{% url 'users:password_reset' %}">Forgotten Password?</a>
                            </div>
                        </div>
                    
                    </form>
                
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/users/register.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

    <section class="vh-100">
        <div class="container py-5 h-100">
            <div class="row d-flex align-items-center justify-content-center h-100">
                <div class="col-md-8 col-lg-7 col-xl-6 mb-3">
                    <img src={% static '/assets/img/login.svg' %} class="img-fluid" alt="Phone image">
                </div>
                <div class="col-md-7 col-lg-5 col-xl-5 offset-xl-1">
                    <div class="d-flex flex-column justify-content-center mb-4 login-header">
                        <h2>New to password manager app? Please sign up and maintain your passwords easily.</h2>
                    </div>
                    <form method='POST'>
                        {% csrf_token %}
                        {% if messages %}
                            <div class="alert alert-primary" role="alert">
                                {% for message in messages %}
                                    {{ message }}
                                {% endfor %}
                            </div>
                        {% endif %}
                        <!-- Username -->
                        <div class="form-floating mb-4">
                            {{ form.username }}
                            <label for="floatingInput">Username</label>
                        </div>
                        <div class="text-danger my-3">{{ form.username.errors }}</div>

                        <!-- Email input -->
                        <div class="form-floating mb-4">
                            {{ form.email }}
                            <label for="floatingInput">Email address</label>
                        </div>
                        <div class="text-danger my-3">{{ form.email.errors }}</div>

                        <!-- Password input -->
                        <div class="form-floating mb-4">
                            {{ form.password1 }}
                            <label for="floatingPassword">Password</label>
                        </div>
                        <div class="text-danger my-3">{{ form.password1.errors }}</div>

                        <!-- Confirm Password input -->
                        <div class="form-floating mb-4">
                            {{ form.password2 }}
                            <label for="confirmfloatingPassword">Confirm Password</label>
                        </div>
                        <div class="text-danger my-3">{{ form.password2.errors }}</div>

                        <!-- Submit button -->
                        <button type="submit" class="btn btn-success btn-lg w-100">Register</button>

                        <div class="divider d-flex align-items-center my-3">
                            <p class="text-center">
                                <a href="{% url "users:login" %}">Already have an account?</a>
                            </p>
                        </div>
                    
                    </form>
                
                </div>
            </div>
        </div>
    </section>

{% endblock %}

templates/users/sub_base.html
{% extends "base.html" %}
{% load static %}
{% block stylesheet %}
    {% static 'css/accounts.css' %}
{% endblock %}

{% block content %}
    <div class="container-fluid">
      <div class="login d-flex align-items-center">
        <div class="col-12 col-md-6  col-lg-6 mx-auto pt-5">
          {% block sub_content %} {% endblock %}
        </div>
      </div>
    </div>
{% endblock %}